---
- hosts: all
  become: true
  connection: ssh
  roles:
    - role: common
      tags:
        - common
    - role: raspberry_pi
    #- role: grafana

- hosts: mgmt
  become: true
  connection: ssh
  roles:
    - role: vim

- hosts: k3s_master
  become: true
  connection: ssh
  roles:
    - role: k3s/master
      tags:
        - k3s_master
    - role: k3s/kubectl
      tags:
        - kubectl

- hosts: k3s_node
  become: true
  connection: ssh
  roles:
    - role: k3s/node
      tags: k3_node

#- hosts: mgmt
  #become: true
  #roles:
    #- role: monitoring 
    #- role: packer
