---
- hosts: all
  become: true
  connection: ssh
  roles:
    - role: common
    - role: raspberry_pi
    - role: grafana

- hosts: k3s_master
  become: true
  connection: ssh
  roles:
    - role: k3s/master
      tags:
        - k3s_master

- hosts: k3s_node
  become: true
  connection: ssh
  roles:
    - role: k3s/node

#- hosts: mgmt
  #become: true
  #roles:
    #- role: monitoring 
    #- role: packer
