- name: Install monitoring packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ monitoring_packages }}"

- name: Download grafana repository key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key
    mode: '0644'

- name: grafana | apt source
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main"
    state: present

- name: Install grafana
  ansible.builtin.package:
    name: grafana
    state: present

- name: Start grafana
  ansible.builtin.service:
    name: grafana-server
    state: started
