- name: Install base packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ base_packages }}"

- name: Update /etc/hosts file
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }}"
    state: present
    regexp: "^{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  loop: "{{ groups['all'] }}"
