- name: Install base packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ base_packages }}"

- name: Install pi4 temperature checking script
  ansible.builtin.copy:
    src: files/check_temp.py
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'

- name: Install cron job to run pi4 check temperature script
  ansible.builtin.cron:
    name: "Check CPU temperature"
    minute: "0/1"
    job: "$PATH:/usr/local/bin /usr/local/bin/check_temp.py -u {{ smtp_user }} -p {{ smtp_password }} -r {{ smtp_user }}"
