- name: Install base packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ base_packages }}"

- name: debug
  debug:
    msg: "HERE"

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: files/check_temp.py
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'

- name: Ensure a job that runs at 2 and 5 exists. Creates an entry like "0 5,2 * * ls -alh > /dev/null"
  ansible.builtin.cron:
    name: "Check CPU temperature"
    minute: "0/1"
    job: "$PATH:/usr/local/bin /usr/local/bin/check_temp.py"

- copy:
    content: "{{ testenc }}"
    dest: "/tmp/testenc"
