- name: Cgroup support
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  register: boot_cmdline

- name: Reboot
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: boot_cmdline.changed

- name: K3s binary arm64
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/v1.27.4+k3s1/k3s-arm64
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/v1.27.4+k3s1/sha256sum-arm64.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  when:
    - ( ansible_facts.architecture is search("arm") and
        ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")

- name: K3s service file
  template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: kubectl binary
  get_url:
    url: https://dl.k8s.io/release/v1.28.0/bin/linux/arm64/kubectl
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: 0755

